/**:
  ros__parameters:
    base_link_length: 0.5
    base_link_width: 0.3
    base_link_height: 0.1
    base_link_mass: 0.25
    wheel_radius: 0.12
    wheel_height: 0.05
    wheel_mass: 2.0
    caster_mass: 0.1