<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="yaml_file" value="$(find diff_drive)/config/robot_size.yaml" />
    <xacro:property name="props" value="${xacro.load_yaml(yaml_file)['/**']['ros__parameters']}" />

    <xacro:property name="base_link_length"  value="${props['base_link_length']}" />
    <xacro:property name="base_link_width"  value="${props['base_link_width']}" />
    <xacro:property name="base_link_height"  value="${props['base_link_height']}" />
    <xacro:property name="base_link_mass"  value="${props['base_link_mass']}" />
    <xacro:property name="wheel_radius"  value="${props['wheel_radius']}" />
    <xacro:property name="wheel_height"  value="${props['wheel_height']}" />
    <xacro:property name="PI"  value="3.1415926535897932" />

    <gazebo>
        <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">
            <left_joint>base_link_to_left_wheel</left_joint>
            <right_joint>base_link_to_right_wheel</right_joint>
            <wheel_separation>${base_link_width+wheel_height}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>50.0</odom_publish_frequency>
            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <tf_topic>/tf</tf_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
        </plugin>

        <plugin name="gz::sim::systems::JointStatePublisher" filename="libgz-sim-joint-state-publisher-system.so">
            <topic>/joint_states</topic>
        </plugin>
    </gazebo>

    <gazebo reference="left_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="right_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="up_caster">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
    </gazebo>

    <gazebo reference="bottom_caster">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
    </gazebo>
</robot>